import { FC } from "react";
import Head from "next/head";

const Home: FC<{}> = () => {
  return (
    <div>
      <Head>
        <title>albotalk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>ALBOTALK</main>

      <footer></footer>
    </div>
  );
};

export default Home;
