import { FC } from "react";
import Head from "next/head";
import { supabase } from "@/base/config/supabase";

const App: FC<{}> = () => {
  const user = supabase.auth.user();

  return (
    <div>
      <Head>
        <title>albotalk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>ALBOTALK App</main>

      <footer></footer>
    </div>
  );
};

export default App;
